project_id = "lfpwubqmpztxhrmxadcl"

[functions.ses-events-webhook]
verify_jwt = false

[functions.pixel-collect]
verify_jwt = false

[functions.pixel-script]
verify_jwt = false

[functions.mcp-server]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.instagram-webhook]
verify_jwt = false

[functions.handle-unsubscribe]
verify_jwt = false

[functions.link-redirect]
verify_jwt = false

[functions.bling-auth]
verify_jwt = false

[functions.data-deletion-callback]
verify_jwt = false

[functions.send-email-ses]
verify_jwt = false


[functions.partner-signup]
verify_jwt = false

[functions.popup-manager]
verify_jwt = false

[functions.clickup-webhook]
verify_jwt = false
